pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
				set JAVA_HOME =C:\Temenos\Temenos\R20\Infra\Java\Default
                bat  "mvn -f java-tomcat-sample/pom.xml clean package"
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'Deploy application war to staging env'

            }
            
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'Deploy application to PROD'
            }
        }
    }
}